### ISSUE TITLE
Add support for jars

### ISSUE THREAD

**Issue by ZAYEC77** [inbalboa/python-monobankua#1]
Hello 👋 
Thank you for this package

Is it possible to add support for `jars` section?

![telegram-cloud-photo-size-2-5201690349259572031-x](https://user-images.githubusercontent.com/4509483/204607421-8607b828-50eb-4f05-9659-26ac6e40136a.jpg)

**Comment by inbalboa** [comment]
Done. Sorry it took so long :-)
